### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Gideon877** [vtrev/bootcamp-tests#1]
@vtrev 

Please fix your tests, none of them are passing.

- Try to include `assert = require('assert')` in all of your test files
-  There is no need to put your code into **gh-pages** branch cause this is not a static site.

@avermeulen

**Comment by vtrev** [comment]
Dude that's front-end; check the one that says terminal tests fro back end.
The mocha and chai tests run on the browser that's why they on gh-pages.


Thanks for checking
